/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory } from "@stencil/router";
export namespace Components {
    interface AppAbout {
        "history": RouterHistory;
    }
    interface AppContactUs {
        "history": RouterHistory;
    }
    interface AppHome {
        "history": RouterHistory;
    }
    interface AppNotFound {
        "history": RouterHistory;
    }
    interface AppPriceList {
        "history": RouterHistory;
    }
    interface AppProduct {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface AppProducts {
        "history": RouterHistory;
    }
    interface AppRoot {
    }
    interface AppTreatment {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface AppTreatments {
        "history": RouterHistory;
    }
    interface NymsAccordion {
        "accordionTitle": string;
        "name"?: string;
        "open": boolean;
    }
    interface NymsFullwidthChat {
    }
    interface NymsFullwidthTestimonial {
    }
    interface NymsGlobalFooter {
    }
    interface NymsGlobalHeader {
    }
    interface NymsSidebarSegment {
        "heading": string;
    }
    interface NymsSidebarTestimonial {
    }
    interface NymsSidebarTreatments {
    }
    interface NymsSocialBar {
    }
    interface OpeningHours {
        "smallTitle": boolean;
    }
}
declare global {
    interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {
    }
    var HTMLAppAboutElement: {
        prototype: HTMLAppAboutElement;
        new (): HTMLAppAboutElement;
    };
    interface HTMLAppContactUsElement extends Components.AppContactUs, HTMLStencilElement {
    }
    var HTMLAppContactUsElement: {
        prototype: HTMLAppContactUsElement;
        new (): HTMLAppContactUsElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppNotFoundElement extends Components.AppNotFound, HTMLStencilElement {
    }
    var HTMLAppNotFoundElement: {
        prototype: HTMLAppNotFoundElement;
        new (): HTMLAppNotFoundElement;
    };
    interface HTMLAppPriceListElement extends Components.AppPriceList, HTMLStencilElement {
    }
    var HTMLAppPriceListElement: {
        prototype: HTMLAppPriceListElement;
        new (): HTMLAppPriceListElement;
    };
    interface HTMLAppProductElement extends Components.AppProduct, HTMLStencilElement {
    }
    var HTMLAppProductElement: {
        prototype: HTMLAppProductElement;
        new (): HTMLAppProductElement;
    };
    interface HTMLAppProductsElement extends Components.AppProducts, HTMLStencilElement {
    }
    var HTMLAppProductsElement: {
        prototype: HTMLAppProductsElement;
        new (): HTMLAppProductsElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTreatmentElement extends Components.AppTreatment, HTMLStencilElement {
    }
    var HTMLAppTreatmentElement: {
        prototype: HTMLAppTreatmentElement;
        new (): HTMLAppTreatmentElement;
    };
    interface HTMLAppTreatmentsElement extends Components.AppTreatments, HTMLStencilElement {
    }
    var HTMLAppTreatmentsElement: {
        prototype: HTMLAppTreatmentsElement;
        new (): HTMLAppTreatmentsElement;
    };
    interface HTMLNymsAccordionElement extends Components.NymsAccordion, HTMLStencilElement {
    }
    var HTMLNymsAccordionElement: {
        prototype: HTMLNymsAccordionElement;
        new (): HTMLNymsAccordionElement;
    };
    interface HTMLNymsFullwidthChatElement extends Components.NymsFullwidthChat, HTMLStencilElement {
    }
    var HTMLNymsFullwidthChatElement: {
        prototype: HTMLNymsFullwidthChatElement;
        new (): HTMLNymsFullwidthChatElement;
    };
    interface HTMLNymsFullwidthTestimonialElement extends Components.NymsFullwidthTestimonial, HTMLStencilElement {
    }
    var HTMLNymsFullwidthTestimonialElement: {
        prototype: HTMLNymsFullwidthTestimonialElement;
        new (): HTMLNymsFullwidthTestimonialElement;
    };
    interface HTMLNymsGlobalFooterElement extends Components.NymsGlobalFooter, HTMLStencilElement {
    }
    var HTMLNymsGlobalFooterElement: {
        prototype: HTMLNymsGlobalFooterElement;
        new (): HTMLNymsGlobalFooterElement;
    };
    interface HTMLNymsGlobalHeaderElement extends Components.NymsGlobalHeader, HTMLStencilElement {
    }
    var HTMLNymsGlobalHeaderElement: {
        prototype: HTMLNymsGlobalHeaderElement;
        new (): HTMLNymsGlobalHeaderElement;
    };
    interface HTMLNymsSidebarSegmentElement extends Components.NymsSidebarSegment, HTMLStencilElement {
    }
    var HTMLNymsSidebarSegmentElement: {
        prototype: HTMLNymsSidebarSegmentElement;
        new (): HTMLNymsSidebarSegmentElement;
    };
    interface HTMLNymsSidebarTestimonialElement extends Components.NymsSidebarTestimonial, HTMLStencilElement {
    }
    var HTMLNymsSidebarTestimonialElement: {
        prototype: HTMLNymsSidebarTestimonialElement;
        new (): HTMLNymsSidebarTestimonialElement;
    };
    interface HTMLNymsSidebarTreatmentsElement extends Components.NymsSidebarTreatments, HTMLStencilElement {
    }
    var HTMLNymsSidebarTreatmentsElement: {
        prototype: HTMLNymsSidebarTreatmentsElement;
        new (): HTMLNymsSidebarTreatmentsElement;
    };
    interface HTMLNymsSocialBarElement extends Components.NymsSocialBar, HTMLStencilElement {
    }
    var HTMLNymsSocialBarElement: {
        prototype: HTMLNymsSocialBarElement;
        new (): HTMLNymsSocialBarElement;
    };
    interface HTMLOpeningHoursElement extends Components.OpeningHours, HTMLStencilElement {
    }
    var HTMLOpeningHoursElement: {
        prototype: HTMLOpeningHoursElement;
        new (): HTMLOpeningHoursElement;
    };
    interface HTMLElementTagNameMap {
        "app-about": HTMLAppAboutElement;
        "app-contact-us": HTMLAppContactUsElement;
        "app-home": HTMLAppHomeElement;
        "app-not-found": HTMLAppNotFoundElement;
        "app-price-list": HTMLAppPriceListElement;
        "app-product": HTMLAppProductElement;
        "app-products": HTMLAppProductsElement;
        "app-root": HTMLAppRootElement;
        "app-treatment": HTMLAppTreatmentElement;
        "app-treatments": HTMLAppTreatmentsElement;
        "nyms-accordion": HTMLNymsAccordionElement;
        "nyms-fullwidth-chat": HTMLNymsFullwidthChatElement;
        "nyms-fullwidth-testimonial": HTMLNymsFullwidthTestimonialElement;
        "nyms-global-footer": HTMLNymsGlobalFooterElement;
        "nyms-global-header": HTMLNymsGlobalHeaderElement;
        "nyms-sidebar-segment": HTMLNymsSidebarSegmentElement;
        "nyms-sidebar-testimonial": HTMLNymsSidebarTestimonialElement;
        "nyms-sidebar-treatments": HTMLNymsSidebarTreatmentsElement;
        "nyms-social-bar": HTMLNymsSocialBarElement;
        "opening-hours": HTMLOpeningHoursElement;
    }
}
declare namespace LocalJSX {
    interface AppAbout {
        "history"?: RouterHistory;
    }
    interface AppContactUs {
        "history"?: RouterHistory;
    }
    interface AppHome {
        "history"?: RouterHistory;
    }
    interface AppNotFound {
        "history"?: RouterHistory;
    }
    interface AppPriceList {
        "history"?: RouterHistory;
    }
    interface AppProduct {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface AppProducts {
        "history"?: RouterHistory;
    }
    interface AppRoot {
    }
    interface AppTreatment {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface AppTreatments {
        "history"?: RouterHistory;
    }
    interface NymsAccordion {
        "accordionTitle": string;
        "name"?: string;
        /**
          * Emitted when the toggle loses focus.
         */
        "onNymsBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the toggle has focus.
         */
        "onNymsFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Emitted when the styles change
         */
        "onNymsStyle"?: (event: CustomEvent<{
    [styleName: string]: boolean;
  }>) => void;
        "open"?: boolean;
    }
    interface NymsFullwidthChat {
    }
    interface NymsFullwidthTestimonial {
        "onRotateQuote"?: (event: CustomEvent<any>) => void;
    }
    interface NymsGlobalFooter {
    }
    interface NymsGlobalHeader {
    }
    interface NymsSidebarSegment {
        "heading"?: string;
    }
    interface NymsSidebarTestimonial {
        "onRotateQuote"?: (event: CustomEvent<any>) => void;
    }
    interface NymsSidebarTreatments {
    }
    interface NymsSocialBar {
    }
    interface OpeningHours {
        "smallTitle"?: boolean;
    }
    interface IntrinsicElements {
        "app-about": AppAbout;
        "app-contact-us": AppContactUs;
        "app-home": AppHome;
        "app-not-found": AppNotFound;
        "app-price-list": AppPriceList;
        "app-product": AppProduct;
        "app-products": AppProducts;
        "app-root": AppRoot;
        "app-treatment": AppTreatment;
        "app-treatments": AppTreatments;
        "nyms-accordion": NymsAccordion;
        "nyms-fullwidth-chat": NymsFullwidthChat;
        "nyms-fullwidth-testimonial": NymsFullwidthTestimonial;
        "nyms-global-footer": NymsGlobalFooter;
        "nyms-global-header": NymsGlobalHeader;
        "nyms-sidebar-segment": NymsSidebarSegment;
        "nyms-sidebar-testimonial": NymsSidebarTestimonial;
        "nyms-sidebar-treatments": NymsSidebarTreatments;
        "nyms-social-bar": NymsSocialBar;
        "opening-hours": OpeningHours;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-about": LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
            "app-contact-us": LocalJSX.AppContactUs & JSXBase.HTMLAttributes<HTMLAppContactUsElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-not-found": LocalJSX.AppNotFound & JSXBase.HTMLAttributes<HTMLAppNotFoundElement>;
            "app-price-list": LocalJSX.AppPriceList & JSXBase.HTMLAttributes<HTMLAppPriceListElement>;
            "app-product": LocalJSX.AppProduct & JSXBase.HTMLAttributes<HTMLAppProductElement>;
            "app-products": LocalJSX.AppProducts & JSXBase.HTMLAttributes<HTMLAppProductsElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-treatment": LocalJSX.AppTreatment & JSXBase.HTMLAttributes<HTMLAppTreatmentElement>;
            "app-treatments": LocalJSX.AppTreatments & JSXBase.HTMLAttributes<HTMLAppTreatmentsElement>;
            "nyms-accordion": LocalJSX.NymsAccordion & JSXBase.HTMLAttributes<HTMLNymsAccordionElement>;
            "nyms-fullwidth-chat": LocalJSX.NymsFullwidthChat & JSXBase.HTMLAttributes<HTMLNymsFullwidthChatElement>;
            "nyms-fullwidth-testimonial": LocalJSX.NymsFullwidthTestimonial & JSXBase.HTMLAttributes<HTMLNymsFullwidthTestimonialElement>;
            "nyms-global-footer": LocalJSX.NymsGlobalFooter & JSXBase.HTMLAttributes<HTMLNymsGlobalFooterElement>;
            "nyms-global-header": LocalJSX.NymsGlobalHeader & JSXBase.HTMLAttributes<HTMLNymsGlobalHeaderElement>;
            "nyms-sidebar-segment": LocalJSX.NymsSidebarSegment & JSXBase.HTMLAttributes<HTMLNymsSidebarSegmentElement>;
            "nyms-sidebar-testimonial": LocalJSX.NymsSidebarTestimonial & JSXBase.HTMLAttributes<HTMLNymsSidebarTestimonialElement>;
            "nyms-sidebar-treatments": LocalJSX.NymsSidebarTreatments & JSXBase.HTMLAttributes<HTMLNymsSidebarTreatmentsElement>;
            "nyms-social-bar": LocalJSX.NymsSocialBar & JSXBase.HTMLAttributes<HTMLNymsSocialBarElement>;
            "opening-hours": LocalJSX.OpeningHours & JSXBase.HTMLAttributes<HTMLOpeningHoursElement>;
        }
    }
}
