/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppAbout {}
  interface AppBook {}
  interface AppContactUs {}
  interface AppHome {}
  interface AppPriceList {}
  interface AppRoot {}
  interface AsideSector {
    'heading': string;
  }
  interface GlobalHeader {}
  interface SocialBar {}
  interface TestimonialSidebar {}
  interface TreatmentSidebar {}
}

declare global {


  interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {}
  var HTMLAppAboutElement: {
    prototype: HTMLAppAboutElement;
    new (): HTMLAppAboutElement;
  };

  interface HTMLAppBookElement extends Components.AppBook, HTMLStencilElement {}
  var HTMLAppBookElement: {
    prototype: HTMLAppBookElement;
    new (): HTMLAppBookElement;
  };

  interface HTMLAppContactUsElement extends Components.AppContactUs, HTMLStencilElement {}
  var HTMLAppContactUsElement: {
    prototype: HTMLAppContactUsElement;
    new (): HTMLAppContactUsElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppPriceListElement extends Components.AppPriceList, HTMLStencilElement {}
  var HTMLAppPriceListElement: {
    prototype: HTMLAppPriceListElement;
    new (): HTMLAppPriceListElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAsideSectorElement extends Components.AsideSector, HTMLStencilElement {}
  var HTMLAsideSectorElement: {
    prototype: HTMLAsideSectorElement;
    new (): HTMLAsideSectorElement;
  };

  interface HTMLGlobalHeaderElement extends Components.GlobalHeader, HTMLStencilElement {}
  var HTMLGlobalHeaderElement: {
    prototype: HTMLGlobalHeaderElement;
    new (): HTMLGlobalHeaderElement;
  };

  interface HTMLSocialBarElement extends Components.SocialBar, HTMLStencilElement {}
  var HTMLSocialBarElement: {
    prototype: HTMLSocialBarElement;
    new (): HTMLSocialBarElement;
  };

  interface HTMLTestimonialSidebarElement extends Components.TestimonialSidebar, HTMLStencilElement {}
  var HTMLTestimonialSidebarElement: {
    prototype: HTMLTestimonialSidebarElement;
    new (): HTMLTestimonialSidebarElement;
  };

  interface HTMLTreatmentSidebarElement extends Components.TreatmentSidebar, HTMLStencilElement {}
  var HTMLTreatmentSidebarElement: {
    prototype: HTMLTreatmentSidebarElement;
    new (): HTMLTreatmentSidebarElement;
  };
  interface HTMLElementTagNameMap {
    'app-about': HTMLAppAboutElement;
    'app-book': HTMLAppBookElement;
    'app-contact-us': HTMLAppContactUsElement;
    'app-home': HTMLAppHomeElement;
    'app-price-list': HTMLAppPriceListElement;
    'app-root': HTMLAppRootElement;
    'aside-sector': HTMLAsideSectorElement;
    'global-header': HTMLGlobalHeaderElement;
    'social-bar': HTMLSocialBarElement;
    'testimonial-sidebar': HTMLTestimonialSidebarElement;
    'treatment-sidebar': HTMLTreatmentSidebarElement;
  }
}

declare namespace LocalJSX {
  interface AppAbout {}
  interface AppBook {}
  interface AppContactUs {}
  interface AppHome {}
  interface AppPriceList {}
  interface AppRoot {}
  interface AsideSector {
    'heading'?: string;
  }
  interface GlobalHeader {}
  interface SocialBar {}
  interface TestimonialSidebar {}
  interface TreatmentSidebar {}

  interface IntrinsicElements {
    'app-about': AppAbout;
    'app-book': AppBook;
    'app-contact-us': AppContactUs;
    'app-home': AppHome;
    'app-price-list': AppPriceList;
    'app-root': AppRoot;
    'aside-sector': AsideSector;
    'global-header': GlobalHeader;
    'social-bar': SocialBar;
    'testimonial-sidebar': TestimonialSidebar;
    'treatment-sidebar': TreatmentSidebar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-about': LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
      'app-book': LocalJSX.AppBook & JSXBase.HTMLAttributes<HTMLAppBookElement>;
      'app-contact-us': LocalJSX.AppContactUs & JSXBase.HTMLAttributes<HTMLAppContactUsElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-price-list': LocalJSX.AppPriceList & JSXBase.HTMLAttributes<HTMLAppPriceListElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'aside-sector': LocalJSX.AsideSector & JSXBase.HTMLAttributes<HTMLAsideSectorElement>;
      'global-header': LocalJSX.GlobalHeader & JSXBase.HTMLAttributes<HTMLGlobalHeaderElement>;
      'social-bar': LocalJSX.SocialBar & JSXBase.HTMLAttributes<HTMLSocialBarElement>;
      'testimonial-sidebar': LocalJSX.TestimonialSidebar & JSXBase.HTMLAttributes<HTMLTestimonialSidebarElement>;
      'treatment-sidebar': LocalJSX.TreatmentSidebar & JSXBase.HTMLAttributes<HTMLTreatmentSidebarElement>;
    }
  }
}


